<?php
/**
 * Author: %%AUTHOR%%
 * URL: %%AUTHORURI%%
 * Description: %%DESCRIPTION%%
 * Version: %%VERSION%%
 */

add_action('wp_head', 'add_header' );

if ( ! function_exists('add_header') ) :
  function add_header() {
    ?>
<!--

      Wij zijn Baldadig
      Author: Baldadig
      AuthorUri: http://baldadig.nl

....................................................................................................
....................................................................................................
......................:dkkkkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkd:......................
....................'dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd'....................
....................:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:....................
....................:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:....................
....................:KMMMMMMMNOOOOOOOOOOOOOO0NMMMMMMMMN0OOOOOOOOOOOOOOXMMMMMMMK:....................
....................:KMMMMMMMk,.............;0MMMMMMMM0;.............,kMMMMMMMK:....................
....................:KMMMMMMMk'.............;0MMMMMMMM0;.............'kMMMMMMMK:....................
....................:KMMMMMMMk'.............;0MMMMMMMM0;.............'kMMMMMMMK:....................
....................:KMMMMMMMk'.............,0MMMMMMMM0;.............'kMMMMMMMK:....................
....................:0MMMMMMMO,.............:KMMMMMMMMK:.............,OMMMMMMMK:....................
....................,kWMMMMMMNd'...........'xWMMMMMMMMWx'...........'dNMMMMMMMk,....................
.....................lXMMMMMMMNk:........'cOWMMMMMMMMMMWOc'........:kNMMMMMMMXl.....................
......................oNMMMMMMMMNOdlcccox0NMMMMMMMMMMMMMMN0xocccldONWMMMMMMMNo......................
.......................lKMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMWKl'......................
........................;xXMMMMMMMMMMMMMMMMMMMMWX00XWMMMMMMMMMMMMMMMMMMMMNx;........................
..........................:d0NMMMMMMMMMMMMMMWN0o;'.;o0NMMMMMMMMMMMMMMMN0d:..........................
............................':ok0KNNWWWNNK0xo:'......':ox0KXNWWWNNX0ko:'............................
.................................,;:::::;'................';;::::;,.................................
....................................................................................................
....................................................................................................

-->
    <?php
  }
endif;
